### ISSUE TITLE
参照API，跑不起来demo

### ISSUE THREAD

**Issue by danlpi** [openkraken/website#120]
FlutterEngine flutterEngine = getFlutterEngine();
getFlutterEngine();找不到，

改成 FlutterEngine flutterEngine = new  FlutterEngine(this); 运行报错如下

 Unhandled Exception: MissingPluginException(No implementation found for method getUrl on channel kraken)

**Comment by wssgcg1213** [comment]
你好, 看起来是插件没有初始化好

**Comment by wssgcg1213** [comment]
可能是你的 Flutter 版本太新了, 使用 1.22.x 试试吧
