### ISSUE TITLE
官网链接无法正常打开

### ISSUE THREAD

**Issue by brizer** [openkraken/website#122]
https://openkraken.com/guide#kraken-playground

官网这里的二维码扫了无法正常打开。。

**Comment by answershuto** [comment]
你说 Playground 吗？是没法下载还是下载了打不开？我试了一下是可以访问的

**Comment by brizer** [comment]
兄弟你给我个包，或者官网除了二维码也给个包链接呗

**Comment by answershuto** [comment]
二维码扫描出来就是 APK 的链接

**Comment by wssgcg1213** [comment]
https://kraken.oss-cn-hangzhou.aliyuncs.com/play-kraken/PlayKraken.v1.0.0.apk
