### ISSUE TITLE
在 JS 环境中与 Native 通信文档问题

### ISSUE THREAD

**Issue by sisychen** [openkraken/website#139]
文档里面写了 Kraken 在 JS 环境中添加了 kraken 的全局对象，在这个全局对象上有 kraken.methodChannel 对象，用于实现和 Native 的消息通信。链接是：https://openkraken.com/guide/advanced/communicate-with-native
前端vue代码无法获取 kraken对象
已执行 npm install -g @openkraken/cli 成功
+ @openkraken/cli@0.8.0
updated 1 package in 11.218s

但是在node_modules目录下没有找到kraken.js文件

**Comment by wssgcg1213** [comment]
你好, kraken 是全局对象, 存在于运行时, 你并不能在 `node_modules` 下面找到 `这个文件`
