### ISSUE TITLE
编译源码完成后，运行报错，flutter版本是2.2.3

### ISSUE THREAD

**Issue by jindingwei** [openkraken/website#154]
When the exception was thrown, this was the stack: 
#2      Layer.engineLayer= (package:flutter/src/rendering/layer.dart:335:12)
#3      ClipRectLayer.addToScene (package:flutter/src/rendering/layer.dart:1368:7)
#4      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#5      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1110:15)
#6      OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1247:5)
#7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1110:15)
#9      OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1247:5)
#10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1110:15)
#12     PhysicalModelLayer.addToScene (package:flutter/src/rendering/layer.dart:2096:5)
#13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1110:15)
#15     OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1247:5)
#16     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#17     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1110:15)
#18     OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:1247:5)
#19     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#20     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1110:15)
#21     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1692:5)
#22     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:941:5)
#23     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:226:37)
#24     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:457:18)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#33     _invoke (dart:ui/hooks.dart:164:10)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:262:5)
#35     _drawFrame (dart:ui/hooks.dart:127:31)
(elided 5 frames from class _AssertionError and dart:async)

**Comment by andycall** [comment]
具体的原因应该在这个堆栈上面

**Comment by andycall** [comment]
看上去是渲染的问题，能提供一份 JS bundle 代码吗？

**Comment by jindingwei** [comment]
> 看上去是渲染的问题，能提供一份 JS bundle 代码吗？

JS Bundle就是Karken/example里面的Helloworld

**Comment by andycall** [comment]
> 具体的原因应该在这个堆栈上面

那不太可能，或许还需要其他的错误信息
