### ISSUE TITLE
请问安卓LoadURL支持file:///吗？

### ISSUE THREAD

**Issue by showtestlog** [openkraken/website#160]
![image](https://user-images.githubusercontent.com/12830799/133227159-30ae42ab-8885-47cb-a65b-3104697db4d5.png)
暂时只能这样从网络远程获取，用file:///android_asset/web/bundle.js 获取本地js文件错误。

**Comment by wssgcg1213** [comment]
你好, 可以提一个 issue 到 https://github.com/openkraken/kraken  

我们之前有一个 issue 讨论使用自定义 Bundle 的形式提供内容的方案, 目前还没有提交 PR   

https://github.com/openkraken/kraken/issues/587
