### ISSUE TITLE
openkraken官网打不开了

### ISSUE THREAD

**Issue by fengqingyun2008** [openkraken/website#171]
openkraken官网打不开了，chrome报警告：
您的连接不是私密连接
攻击者可能会试图从 openkraken.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
NET::ERR_CERT_DATE_INVALID
openkraken.com 通常会使用加密技术来保护您的信息。Chrome 此次尝试连接到 openkraken.com 时，该网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 openkraken.com，或者 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 openkraken.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by cnryb** [comment]
就是证书过期了。和 #170 的问题一样，放一起处理吧。

**Comment by cnryb** [comment]
暂时可以使用无痕模式访问 http://openkraken.com/

**Comment by wssgcg1213** [comment]
@fengqingyun2008 你好, 已经处理完毕, 更新了证书
