### ISSUE TITLE
Flutter Widget 封装自定义组件 在dispatchEvent中传参

### ISSUE THREAD

**Issue by yuchonghua** [openkraken/website#199]
[Flutter Widget 封装自定义组件 在dispatchEvent中传参](https://openkraken.com/guide/advanced/widget-custom-element), widget 可以通过 dispatchEvent 将自定义事件抛给前端监听，[如何在dispatchEvent中传参](https://github.com/openkraken/kraken/issues/1162#issuecomment-1048378522)

**Comment by answershuto** [comment]
可以用 CustomEvent
