### ISSUE TITLE
kraken android sdk在哪下载啊？

### ISSUE THREAD

**Issue by hanxiaofeng** [openkraken/website#221]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/10582931/168940635-ad756524-367e-41a0-bc1f-01b12e8efbdc.png">

1.kraken android sdk在哪下载啊？没找到下载位置

**Comment by wssgcg1213** [comment]
0.10 之后我们没有再提供预构建的 Android/iOS SDK 了，需要自行使用 Flutter tools 构建

**Comment by hanxiaofeng** [comment]
@wssgcg1213 有如何构建sdk的文档吗

**Comment by andycall** [comment]
@wssgcg1213 这种方式已经停止维护了，我们应该把文档也去掉
